spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order-service
    hikari:
      username: postgres
      password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081