spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-service
    hikari:
      username: postgres
      password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8082